name: Publish to NPM registry

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: https://registry.npmjs.com/
          cache: pnpm

      - name: Get version
        run: echo "PACKAGE_VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"

      - name: Get git head
        run: echo "GIT_HEAD=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build&publish
        run: sh ./scripts/publish.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
          TAG_VERSION: ${{ env.PACKAGE_VERSION }}
          GIT_HEAD: ${{ env.GIT_HEAD }}
          REGISTRY: https://registry.npmjs.com/
          NODE_OPTIONS: --max-old-space-size=4096
      
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          dependencies: false
          extensionFile: packages/extension/b-reader-${{ env.PACKAGE_VERSION }}.vsix
          registryUrl: https://marketplace.visualstudio.com
    
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          dependencies: false
          extensionFile: packages/extension/b-reader-${{ env.PACKAGE_VERSION }}.vsix
